server:
  port: 7002
spring:
  application:
    name: regist-client
eureka:
  client:
    service-url:
      defaultZone: http://server0:8000/eureka/,http://server1:8001/eureka/,http://server2:8002/eureka/
  instance:
    hostname: localhost

